version: '3.0'
services:
  bot:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    links:
      - db
      - redis
    container_name: playstationpt_bot
    volumes:
      - ./:/app:rw
      - /app/node_modules
    env_file:
      - .env

  db:
    image: mysql:5.6
    platform: linux/x86_64
    container_name: playstationpt_db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'bot'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'pw'
    volumes:
      - ./docker/db:/var/lib/mysql:rw
    ports:
      - "3306:3306"

  redis:
    image: redis:bullseye
    container_name: playstationpt_redis
    volumes:
      - ./docker/redis/redis-data:/var/lib/redis/data:rw
    ports:
      - "6379:6379"
